-- 架空の「青空運送」デモ。会社、取引先、市場、競合、数値はすべて架空。
INSERT INTO public.knowledge_items
(code, kind, title, content, owner_code, region, aliases, status, valid_from, valid_to, source_uri, metadata)
VALUES
('CODE-001', 'CODE', '青空運送のコード体系', '識別子は種別接頭辞とハイフンと英大文字・数字で構成する。ORGは組織、TERMは用語、FLOWは工程、SVCはサービス、CUSTは荷主、RULEは規程、NEEDはニーズ、KPIは指標、INDは業界観測、COMPは競合観測。識別子は再利用せず改訂時も出典と有効期間を保持する。', 'ORG-STRATEGY', '全国', 'コード体系 識別子 マスタ', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/CODE-001', '{}'),
('CODE-002', 'CODE', '荷物・便・温度帯のコード', '荷物番号はAZと受付日8桁と連番6桁。便番号はLNと拠点対と出発日。温度帯AMBは常温、CHLは冷蔵2〜8度、FRZは冷凍マイナス18度以下。SVC-COLDはCHLのみを扱い、冷凍を混載しない。', 'ORG-OPS', '全国', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/CODE-002', '{}'),
('CODE-003', 'CODE', '例外と配送状態のコード', '状態はRECEIVED→PLANNED→PICKED_UP→IN_TRANSIT→DELIVERED。例外TEMPは温度逸脱、SNOWは雪害、ABSENTは不在、DAMAGEは破損。例外発生時は自動的な配送完了にせず責任者の判断を記録する。', 'ORG-QUALITY', '全国', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/CODE-003', '{}'),
('TERM-OTIF', 'TERM', '納期内・全量納品率', '約束日時までに欠品なく納品した件数を対象納品件数で割る。顧客合意の納期変更を分母から除外しない。遅延と欠品の重複は1件として数える。', 'ORG-QUALITY', '全国', '納期遵守 完納率', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/TERM-OTIF', '{}'),
('TERM-POD', 'TERM', '配達完了証跡', '受領者名・受領時刻・荷物番号を記録した電子受領証。冷蔵配送では引渡温度も関連付ける。写真は同意を得て取得し閲覧権限を限定する。', 'ORG-QUALITY', '全国', '電子受領証 配達証明', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/TERM-POD', '{}'),
('TERM-CROSSDOCK', 'TERM', 'クロスドック', '入荷貨物を長期保管せず仕分けして別便へ積み替える方式。冷蔵品は保冷ヤードを使い、待機が30分を超えたら品質管理室へ連絡する。', 'ORG-QUALITY', '全国', '積替え 中継', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/TERM-CROSSDOCK', '{}'),
('TERM-LOADFACTOR', 'TERM', '積載率', '利用可能な重量容量に対する実積載重量の割合。容積制約も併記し、重量だけで共同配送の可否を判断しない。', 'ORG-QUALITY', '全国', '積載効率', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/TERM-LOADFACTOR', '{}'),
('TERM-COLDCHAIN', 'TERM', 'コールドチェーン', '集荷から引渡しまで温度条件を継続して維持する仕組み。逸脱は荷主への通知と隔離判断を伴う。', 'ORG-QUALITY', '全国', '低温物流 冷蔵 温度管理', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/TERM-COLDCHAIN', '{}'),
('TERM-SLA', 'TERM', 'サービス水準合意', '納期・温度帯・通知期限・証跡提供時間を荷主と合意した契約条件。標準規程より厳しい条件は営業と品質管理室の承認が必要。', 'ORG-QUALITY', '全国', 'サービスレベル 合意水準', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/TERM-SLA', '{}'),
('ORG-HQ', 'ORG', '本社', '経営方針と投資配分を決定する。営業本部、運行本部、品質管理室、経営企画室を統括する。', 'ORG-HQ', '全国', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/ORG-HQ', '{}'),
('ORG-STRATEGY', 'ORG', '経営企画室', '地域別の利益率・積載率・品質コストを月次集計する。共同配送への投資と試行継続を経営会議へ提案する。', 'ORG-HQ', '全国', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/ORG-STRATEGY', '{}'),
('ORG-SALES', 'ORG', '営業本部', '荷主のSLAを契約へ落とし込み、追加料金・例外通知先・納期変更を合意する。現場判断での無償特急化は承認しない。', 'ORG-HQ', '全国', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/ORG-SALES', '{}'),
('ORG-OPS', 'ORG', '運行本部', '配車・中継・配送の標準手順を所管し拠点間の応援を調整する。品質判断の権限は品質管理室に残す。', 'ORG-HQ', '全国', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/ORG-OPS', '{}'),
('ORG-QUALITY', 'ORG', '品質管理室', '温度逸脱時の隔離と出荷再開を判定する。荷主との安全確認が完了するまで再配送を承認しない。', 'ORG-HQ', '全国', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/ORG-QUALITY', '{}'),
('ORG-SAPPORO', 'ORG', '札幌センター', '北海道内の配送と雪害時の代替便を運行本部に提案する。前日16時に翌日遅延の見込みを共有する。', 'ORG-HQ', '北海道', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/ORG-SAPPORO', '{}'),
('ORG-TOKYO', 'ORG', '東京ハブ', '関東荷主の集荷と北海道向け幹線積載を担当する。冷蔵品の引継ぎ温度と荷姿を照合する。', 'ORG-HQ', '全国', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/ORG-TOKYO', '{}'),
('ORG-IT', 'ORG', '情報システム室', '配送イベント連携と電子PODの障害対応を担う。通信断時の端末保存データを復旧後に重複なく同期する。', 'ORG-HQ', '全国', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/ORG-IT', '{}'),
('FLOW-RECEIVE', 'FLOW', '受注・SLA確認', '営業担当が荷主コード、温度帯、納期、通知先を確認し受注を確定する。不明な温度条件は受注を保留し品質管理室へ照会する。', 'ORG-SALES', '全国', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/FLOW-RECEIVE', '{}'),
('FLOW-PLAN', 'FLOW', '配車・便組成', '配車担当が重量・容積・運転時間・温度帯で便を組成する。雪害予測時は札幌センターへ確認し荷主合意後に予定を変更する。', 'ORG-OPS', '全国', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/FLOW-PLAN', '{}'),
('FLOW-PICKUP', 'FLOW', '集荷・検品', 'ドライバーが荷物コードと温度と荷姿を照合する。破損または2〜8度外の冷蔵品は積み込まず写真と温度を報告する。', 'ORG-TOKYO', '全国', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/FLOW-PICKUP', '{}'),
('FLOW-TRANSFER', 'FLOW', '幹線輸送・中継', '東京ハブから札幌センターへ幹線輸送し、中継時に封印番号・温度履歴を引き継ぐ。冷蔵ヤード待機30分超は品質管理室へ報告する。', 'ORG-OPS', '全国', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/FLOW-TRANSFER', '{}'),
('FLOW-DELIVER', 'FLOW', '納品・POD登録', '受領者と数量を照合しPODを登録する。通信断では端末内に保存し、復旧後に同期する。温度逸脱があれば納品を止め隔離する。', 'ORG-SAPPORO', '全国', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/FLOW-DELIVER', '{}'),
('FLOW-EXCEPTION', 'FLOW', '例外・荷主通知', '現場が例外コードを登録し配車担当へ即時連絡する。品質管理室が温度逸脱品を判定し、営業は検知後30分以内に荷主へ第一報を行う。', 'ORG-QUALITY', '全国', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/FLOW-EXCEPTION', '{}'),
('FLOW-BILLING', 'FLOW', '請求・品質振り返り', '営業が契約料金と追加費用の承認証跡を照合する。経営企画室が週次で遅延原因・温度逸脱・再配達コストを振り返る。', 'ORG-STRATEGY', '全国', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/FLOW-BILLING', '{}'),
('SVC-STANDARD', 'SERVICE', 'あおぞら標準便', '常温の法人向け混載配送。15時受付締切、翌営業日出荷。離島と冬季北海道は追加日数を見積もり時に提示する。', 'ORG-SALES', '全国', '常温 混載', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/SVC-STANDARD', '{}'),
('SVC-COLD', 'SERVICE', 'あおぞらチルド便', '法人向け冷蔵食品配送。2〜8度を維持し、集荷・中継・納品の温度を記録する。冷凍品・医薬品は対象外。納品後2時間以内にPODを提供する。', 'ORG-SALES', '全国', '冷蔵 コールドチェーン チルド', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/SVC-COLD', '{}'),
('SVC-JOINT', 'SERVICE', '地域共同配送', '複数荷主の納品先と時間帯を束ねるサービス。温度帯・荷姿・荷主の混載同意が一致した場合のみ組成する。2026年度は北海道と関東で試行する。', 'ORG-SALES', '全国', '共同物流 積載率', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/SVC-JOINT', '{}'),
('SVC-VISIBILITY', 'SERVICE', '配送可視化オプション', '配送状態、到着見込み、温度例外、電子PODを荷主へ共有する。位置情報の公開対象は担当荷主の貨物に限定する。', 'ORG-SALES', '全国', '追跡 トラッキング POD', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/SVC-VISIBILITY', '{}'),
('CUST-FOOD', 'PARTNER', '北星フーズ', '架空の北海道食品メーカー。首都圏への乳製品出荷と札幌小売店への補充配送を依頼する。冷蔵2〜8度と店舗午前納品を契約条件とする。', 'ORG-SALES', '北海道', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/CUST-FOOD', '{}'),
('CUST-RETAIL', 'PARTNER', 'みらいマート', '架空の小売チェーン。店舗の荷受け人員が少ないため配送時刻の分散とPODの早期提供を求める。予約枠を超える納品は店舗と再調整する。', 'ORG-SALES', '全国', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/CUST-RETAIL', '{}'),
('CUST-PARTS', 'PARTNER', '東都精機', '架空の部品メーカー。常温部品を関東工場へ定時配送する。緊急便は費用の事前承認と追跡情報を必要とする。', 'ORG-SALES', '関東', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/CUST-PARTS', '{}'),
('RULE-001', 'RULE', '通常配送の受付締切', '通常配送は営業日15時までの受付で翌営業日に出荷する。離島の到着日は個別見積もりとし翌日到着を保証しない。', 'ORG-OPS', '全国', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/RULE-001', '{}'),
('RULE-002', 'RULE', '冷蔵品の温度管理', '冷蔵品は2〜8度で輸送する。集荷・中継・引渡時の温度を記録し、逸脱時は隔離して品質管理室へ連絡する。荷主確認前に再配送しない。', 'ORG-QUALITY', '全国', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/RULE-002', '{}'),
('RULE-003', 'RULE', '北海道の冬季配送', '12月から3月の北海道は通常予定に2営業日を追加する。雪害予測時は札幌センターが前日16時に見込みを連絡し、営業が荷主と納期を再合意する。', 'ORG-SAPPORO', '北海道', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/RULE-003', '{}'),
('RULE-004', 'RULE', '例外の第一報と判断権限', '温度逸脱は検知後30分以内に営業から荷主へ第一報する。出荷再開は品質管理室が荷主と確認して承認し、現場単独では判断しない。', 'ORG-QUALITY', '全国', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/RULE-004', '{}'),
('RULE-005', 'RULE', '共同配送の混載条件', '荷主の書面同意・同一温度帯・汚染リスクのない荷姿が条件。未承認の食品と化学品の混載を禁止する。低積載でも条件を省略しない。', 'ORG-OPS', '全国', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/RULE-005', '{}'),
('RULE-006', 'RULE', 'PODの提供期限', '冷蔵便は納品後2時間以内に電子PODを荷主へ提供する。通信断時は営業へ第一報し、端末保存から復旧後に同期する。', 'ORG-IT', '全国', '', 'APPROVED', '2026-04-01', NULL, 'demo://aozora/2026/RULE-006', '{}'),
('RULE-007', 'RULE', '追加費用の承認', '特急便と待機料は営業が荷主へ事前提示して承認番号を記録する。雪害迂回費用も自動請求せず契約を確認する。', 'ORG-SALES', '全国', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/RULE-007', '{}'),
('RULE-008', 'RULE', '旧POD翌営業日提供', '旧手順はPODを翌営業日までに提供していた。2026年4月1日以降はRULE-006を参照する。', 'ORG-IT', '全国', '旧規程', 'RETIRED', '2025-01-01', '2026-04-01', 'demo://aozora/2026/RULE-008', '{}'),
('NEED-MARGIN', 'MANAGEMENT_NEED', '低温配送の利益率改善', '経営会議の架空目標：冷蔵便営業利益率を2026年度末までに5%から8%へ改善する。安全基準を維持し、積載率向上と再配送削減を先に試行する。', 'ORG-STRATEGY', '全国', '', 'PROPOSED', '2026-01-01', NULL, 'demo://aozora/2026/NEED-MARGIN', '{}'),
('NEED-QUALITY', 'MANAGEMENT_NEED', '品質と収益の両立', '月次の温度逸脱率を0.8%から0.3%以下へ改善する。品質管理室が原因別件数、営業が補償費、経営企画室が利益への影響を確認する。', 'ORG-STRATEGY', '全国', '', 'PROPOSED', '2026-01-01', NULL, 'demo://aozora/2026/NEED-QUALITY', '{}'),
('NEED-CAPACITY', 'MANAGEMENT_NEED', '繁忙期の輸送力確保', '冬季の予備車両と協力会社枠を確保し、無理な配車を避ける。共同配送の継続判断は利益だけでなく待機時間と品質を含める。', 'ORG-OPS', '全国', '', 'PROPOSED', '2026-01-01', NULL, 'demo://aozora/2026/NEED-CAPACITY', '{}'),
('NEED-FRESH', 'CUSTOMER_NEED', '北星フーズの鮮度・午前納品', '北星フーズは冷蔵2〜8度、店舗午前納品、温度履歴の提出を求める。雪害時も無断で納期変更せず代替日と影響数量を30分以内の第一報後に協議する。', 'ORG-SALES', '全国', '', 'PROPOSED', '2026-01-01', NULL, 'demo://aozora/2026/NEED-FRESH', '{}'),
('NEED-POD', 'CUSTOMER_NEED', 'みらいマートの検収省力化', 'みらいマートはPODを納品後2時間以内に受領し、荷物番号で発注データと照合したい。荷受けの集中を避けるため予約枠の分散も要求する。', 'ORG-SALES', '全国', '', 'PROPOSED', '2026-01-01', NULL, 'demo://aozora/2026/NEED-POD', '{}'),
('NEED-TRACE', 'CUSTOMER_NEED', '東都精機の緊急便可視化', '東都精機は生産停止を避けるため到着見込みと遅延通知を求める。特急料金の承認者が不在なら標準便からの切替を保留する。', 'ORG-SALES', '全国', '', 'PROPOSED', '2026-01-01', NULL, 'demo://aozora/2026/NEED-TRACE', '{}'),
('NEED-OFFLINE', 'FIELD_NEED', '通信断でも検品・PODを記録', '札幌センターの現場は通信不安定区間で温度と受領証を端末保存したい。同期時の二重登録を荷物番号とイベントIDで防止する。', 'ORG-SAPPORO', '北海道', '', 'PROPOSED', '2026-01-01', NULL, 'demo://aozora/2026/NEED-OFFLINE', '{}'),
('NEED-WAIT', 'FIELD_NEED', '待機と二重入力の削減', 'ドライバーは店舗待機を1納品平均45分から20分以内へ減らしたい。予約枠共有と荷物コードのスキャンで事務所への再入力をなくす。', 'ORG-OPS', '全国', '', 'PROPOSED', '2026-01-01', NULL, 'demo://aozora/2026/NEED-WAIT', '{}'),
('NEED-AUTHORITY', 'FIELD_NEED', '温度逸脱の判断先を明確化', '現場は温度逸脱時に誰へ連絡し、誰が再開を承認するかを知りたい。経営の利益目標より隔離と荷主確認を優先する。', 'ORG-QUALITY', '全国', '', 'PROPOSED', '2026-01-01', NULL, 'demo://aozora/2026/NEED-AUTHORITY', '{}'),
('KPI-MARGIN', 'KPI', '冷蔵便営業利益率', '冷蔵便の営業利益÷冷蔵便売上。目標8%、架空基準値5%。経営企画室が月次集計し、補償費と再配送費を含める。', 'ORG-STRATEGY', '全国', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/KPI-MARGIN', '{}'),
('KPI-OTIF', 'KPI', '店舗OTIF', '納期内・全量納品件数÷対象納品件数。目標98%、架空基準値94%。営業本部が荷主別・拠点別に週次確認する。', 'ORG-STRATEGY', '全国', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/KPI-OTIF', '{}'),
('KPI-LOAD', 'KPI', '重量積載率', '実積載重量÷利用可能重量容量。目標75%、架空基準値60%。容積利用率と温度条件を併記する。', 'ORG-STRATEGY', '全国', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/KPI-LOAD', '{}'),
('KPI-TEMP', 'KPI', '温度逸脱率', '温度逸脱のあった冷蔵配送件数÷冷蔵配送件数。目標0.3%以下、架空基準値0.8%。品質管理室が週次監視する。', 'ORG-STRATEGY', '全国', '', 'APPROVED', '2026-01-01', NULL, 'demo://aozora/2026/KPI-TEMP', '{}'),
('IND-CAPACITY', 'INDUSTRY', '輸送力制約のシナリオ', '架空の市場観測：繁忙期の協力会社枠が不足する想定。共同配送と荷主の納品時間調整で対応する。実際の法令や市場統計を示す情報ではない。', 'ORG-STRATEGY', '全国', '業界動向 市場 仮説', 'OBSERVATION', '2026-07-01', NULL, 'demo://aozora/2026/IND-CAPACITY', '{}'),
('IND-TRACE', 'INDUSTRY', '温度・配送証跡要求のシナリオ', '架空の市場観測：荷主が温度履歴と電子PODを重視する想定。配送可視化サービスへの投資仮説であり、受注増加を保証しない。', 'ORG-STRATEGY', '全国', '業界動向 市場 仮説', 'OBSERVATION', '2026-07-01', NULL, 'demo://aozora/2026/IND-TRACE', '{}'),
('IND-GREEN', 'INDUSTRY', '環境配慮調達のシナリオ', '架空の市場観測：荷主が空車回送削減と共同配送を評価する想定。排出量は計測条件を明示し、実測前に削減率を宣伝しない。', 'ORG-STRATEGY', '全国', '業界動向 市場 仮説', 'OBSERVATION', '2026-07-01', NULL, 'demo://aozora/2026/IND-GREEN', '{}'),
('COMP-SNOW', 'COMPETITOR', '白銀ロジの冬季配送', '架空の競合・白銀ロジは北海道の予備便と地場ネットワークを強みとする想定。価格は未調査。青空運送は温度証跡と荷主通知で差別化する仮説を立てる。', 'ORG-STRATEGY', '北海道', '競合動向 比較 仮説', 'OBSERVATION', '2026-07-01', NULL, 'demo://aozora/2026/COMP-SNOW', '{}'),
('COMP-DIGITAL', 'COMPETITOR', 'ネクストカーゴの可視化', '架空の競合・ネクストカーゴは到着予測とPODポータルを提供する想定。公開デモ相当の仮説であり精度の比較は未検証。青空運送は通信断対応を試行する。', 'ORG-STRATEGY', '全国', '競合動向 比較 仮説', 'OBSERVATION', '2026-07-01', NULL, 'demo://aozora/2026/COMP-DIGITAL', '{}'),
('COMP-JOINT', 'COMPETITOR', 'つばさ共同便の混載', '架空の競合・つばさ共同便は地域共同配送による低価格を訴求する想定。収益性は不明。青空運送は混載条件を維持しながら積載率を検証する。', 'ORG-STRATEGY', '関東', '競合動向 比較 仮説', 'OBSERVATION', '2026-07-01', NULL, 'demo://aozora/2026/COMP-JOINT', '{}');

INSERT INTO public.knowledge_relations (source_code, target_code, relation, rationale)
VALUES
('CODE-001', 'ORG-STRATEGY', 'OWNED_BY', '情報の主管・問い合わせ先'),
('CODE-002', 'ORG-OPS', 'OWNED_BY', '情報の主管・問い合わせ先'),
('CODE-003', 'ORG-QUALITY', 'OWNED_BY', '情報の主管・問い合わせ先'),
('TERM-OTIF', 'ORG-QUALITY', 'OWNED_BY', '情報の主管・問い合わせ先'),
('TERM-POD', 'ORG-QUALITY', 'OWNED_BY', '情報の主管・問い合わせ先'),
('TERM-CROSSDOCK', 'ORG-QUALITY', 'OWNED_BY', '情報の主管・問い合わせ先'),
('TERM-LOADFACTOR', 'ORG-QUALITY', 'OWNED_BY', '情報の主管・問い合わせ先'),
('TERM-COLDCHAIN', 'ORG-QUALITY', 'OWNED_BY', '情報の主管・問い合わせ先'),
('TERM-SLA', 'ORG-QUALITY', 'OWNED_BY', '情報の主管・問い合わせ先'),
('FLOW-RECEIVE', 'ORG-SALES', 'OWNED_BY', '情報の主管・問い合わせ先'),
('FLOW-PLAN', 'ORG-OPS', 'OWNED_BY', '情報の主管・問い合わせ先'),
('FLOW-PICKUP', 'ORG-TOKYO', 'OWNED_BY', '情報の主管・問い合わせ先'),
('FLOW-TRANSFER', 'ORG-OPS', 'OWNED_BY', '情報の主管・問い合わせ先'),
('FLOW-DELIVER', 'ORG-SAPPORO', 'OWNED_BY', '情報の主管・問い合わせ先'),
('FLOW-EXCEPTION', 'ORG-QUALITY', 'OWNED_BY', '情報の主管・問い合わせ先'),
('FLOW-BILLING', 'ORG-STRATEGY', 'OWNED_BY', '情報の主管・問い合わせ先'),
('SVC-STANDARD', 'ORG-SALES', 'OWNED_BY', '情報の主管・問い合わせ先'),
('SVC-COLD', 'ORG-SALES', 'OWNED_BY', '情報の主管・問い合わせ先'),
('SVC-JOINT', 'ORG-SALES', 'OWNED_BY', '情報の主管・問い合わせ先'),
('SVC-VISIBILITY', 'ORG-SALES', 'OWNED_BY', '情報の主管・問い合わせ先'),
('CUST-FOOD', 'ORG-SALES', 'OWNED_BY', '情報の主管・問い合わせ先'),
('CUST-RETAIL', 'ORG-SALES', 'OWNED_BY', '情報の主管・問い合わせ先'),
('CUST-PARTS', 'ORG-SALES', 'OWNED_BY', '情報の主管・問い合わせ先'),
('RULE-001', 'ORG-OPS', 'OWNED_BY', '情報の主管・問い合わせ先'),
('RULE-002', 'ORG-QUALITY', 'OWNED_BY', '情報の主管・問い合わせ先'),
('RULE-003', 'ORG-SAPPORO', 'OWNED_BY', '情報の主管・問い合わせ先'),
('RULE-004', 'ORG-QUALITY', 'OWNED_BY', '情報の主管・問い合わせ先'),
('RULE-005', 'ORG-OPS', 'OWNED_BY', '情報の主管・問い合わせ先'),
('RULE-006', 'ORG-IT', 'OWNED_BY', '情報の主管・問い合わせ先'),
('RULE-007', 'ORG-SALES', 'OWNED_BY', '情報の主管・問い合わせ先'),
('RULE-008', 'ORG-IT', 'OWNED_BY', '情報の主管・問い合わせ先'),
('NEED-MARGIN', 'ORG-STRATEGY', 'OWNED_BY', '情報の主管・問い合わせ先'),
('NEED-QUALITY', 'ORG-STRATEGY', 'OWNED_BY', '情報の主管・問い合わせ先'),
('NEED-CAPACITY', 'ORG-OPS', 'OWNED_BY', '情報の主管・問い合わせ先'),
('NEED-FRESH', 'ORG-SALES', 'OWNED_BY', '情報の主管・問い合わせ先'),
('NEED-POD', 'ORG-SALES', 'OWNED_BY', '情報の主管・問い合わせ先'),
('NEED-TRACE', 'ORG-SALES', 'OWNED_BY', '情報の主管・問い合わせ先'),
('NEED-OFFLINE', 'ORG-SAPPORO', 'OWNED_BY', '情報の主管・問い合わせ先'),
('NEED-WAIT', 'ORG-OPS', 'OWNED_BY', '情報の主管・問い合わせ先'),
('NEED-AUTHORITY', 'ORG-QUALITY', 'OWNED_BY', '情報の主管・問い合わせ先'),
('KPI-MARGIN', 'ORG-STRATEGY', 'OWNED_BY', '情報の主管・問い合わせ先'),
('KPI-OTIF', 'ORG-STRATEGY', 'OWNED_BY', '情報の主管・問い合わせ先'),
('KPI-LOAD', 'ORG-STRATEGY', 'OWNED_BY', '情報の主管・問い合わせ先'),
('KPI-TEMP', 'ORG-STRATEGY', 'OWNED_BY', '情報の主管・問い合わせ先'),
('IND-CAPACITY', 'ORG-STRATEGY', 'OWNED_BY', '情報の主管・問い合わせ先'),
('IND-TRACE', 'ORG-STRATEGY', 'OWNED_BY', '情報の主管・問い合わせ先'),
('IND-GREEN', 'ORG-STRATEGY', 'OWNED_BY', '情報の主管・問い合わせ先'),
('COMP-SNOW', 'ORG-STRATEGY', 'OWNED_BY', '情報の主管・問い合わせ先'),
('COMP-DIGITAL', 'ORG-STRATEGY', 'OWNED_BY', '情報の主管・問い合わせ先'),
('COMP-JOINT', 'ORG-STRATEGY', 'OWNED_BY', '情報の主管・問い合わせ先'),
('ORG-STRATEGY', 'ORG-HQ', 'REPORTS_TO', '本社の機能組織'),
('ORG-SALES', 'ORG-HQ', 'REPORTS_TO', '本社の機能組織'),
('ORG-OPS', 'ORG-HQ', 'REPORTS_TO', '本社の機能組織'),
('ORG-QUALITY', 'ORG-HQ', 'REPORTS_TO', '本社の機能組織'),
('ORG-IT', 'ORG-HQ', 'REPORTS_TO', '本社の機能組織'),
('ORG-SAPPORO', 'ORG-OPS', 'REPORTS_TO', '運行本部が管轄する拠点'),
('ORG-TOKYO', 'ORG-OPS', 'REPORTS_TO', '運行本部が管轄する拠点'),
('FLOW-RECEIVE', 'FLOW-PLAN', 'NEXT', '通常配送の次工程'),
('FLOW-PLAN', 'FLOW-PICKUP', 'NEXT', '通常配送の次工程'),
('FLOW-PICKUP', 'FLOW-TRANSFER', 'NEXT', '通常配送の次工程'),
('FLOW-TRANSFER', 'FLOW-DELIVER', 'NEXT', '通常配送の次工程'),
('FLOW-DELIVER', 'FLOW-BILLING', 'NEXT', '通常配送の次工程'),
('FLOW-PICKUP', 'FLOW-EXCEPTION', 'ON_EXCEPTION', '温度逸脱・破損・遅延時の分岐'),
('FLOW-TRANSFER', 'FLOW-EXCEPTION', 'ON_EXCEPTION', '温度逸脱・破損・遅延時の分岐'),
('FLOW-DELIVER', 'FLOW-EXCEPTION', 'ON_EXCEPTION', '温度逸脱・破損・遅延時の分岐'),
('SVC-COLD', 'RULE-002', 'GOVERNED_BY', '冷蔵便の温度制約'),
('SVC-COLD', 'RULE-006', 'GOVERNED_BY', '冷蔵便の証跡期限'),
('SVC-STANDARD', 'RULE-001', 'GOVERNED_BY', '標準受付締切'),
('SVC-JOINT', 'RULE-005', 'GOVERNED_BY', '混載の承認条件'),
('RULE-003', 'RULE-001', 'EXTENDS', '冬季北海道の追加日数'),
('RULE-002', 'RULE-004', 'ESCALATES_TO', '温度逸脱時の連絡と権限'),
('RULE-006', 'RULE-008', 'SUPERSEDES', '2026年4月から提供期限を短縮'),
('FLOW-EXCEPTION', 'RULE-004', 'GOVERNED_BY', '第一報30分以内・再開承認'),
('FLOW-DELIVER', 'RULE-006', 'GOVERNED_BY', '納品後の証跡提供'),
('FLOW-PLAN', 'RULE-003', 'GOVERNED_BY', '冬季北海道の配車判断'),
('FLOW-PLAN', 'RULE-005', 'GOVERNED_BY', '混載の適合確認'),
('CUST-FOOD', 'NEED-FRESH', 'REQUESTS', '荷主の鮮度と納期要求'),
('CUST-RETAIL', 'NEED-POD', 'REQUESTS', '検収省力化の要求'),
('CUST-PARTS', 'NEED-TRACE', 'REQUESTS', '緊急便の要求'),
('NEED-FRESH', 'SVC-COLD', 'ADDRESSED_BY', '冷蔵便で温度条件を担保'),
('NEED-FRESH', 'RULE-003', 'CONSTRAINED_BY', '午前納品と冬季遅延の調整が必要'),
('NEED-POD', 'SVC-VISIBILITY', 'ADDRESSED_BY', '電子POD共有'),
('NEED-TRACE', 'SVC-VISIBILITY', 'ADDRESSED_BY', '到着見込み共有'),
('NEED-MARGIN', 'SVC-JOINT', 'ADDRESSED_BY', '積載率向上で収益を改善する仮説'),
('NEED-CAPACITY', 'SVC-JOINT', 'ADDRESSED_BY', '便を共同化し輸送力を確保'),
('NEED-QUALITY', 'RULE-002', 'CONSTRAINED_BY', '品質基準を削減しない'),
('NEED-MARGIN', 'NEED-QUALITY', 'BALANCED_WITH', '収益改善で温度管理を省略しない'),
('NEED-OFFLINE', 'SVC-VISIBILITY', 'ADDRESSED_BY', '端末保存と再同期'),
('NEED-WAIT', 'FLOW-RECEIVE', 'ADDRESSED_BY', '受注時の予約枠合意'),
('NEED-AUTHORITY', 'RULE-004', 'ADDRESSED_BY', '判断権限を明文化'),
('NEED-MARGIN', 'KPI-MARGIN', 'MEASURED_BY', '月次利益率'),
('NEED-QUALITY', 'KPI-TEMP', 'MEASURED_BY', '温度逸脱率'),
('NEED-FRESH', 'KPI-OTIF', 'MEASURED_BY', '荷主納期と欠品'),
('SVC-JOINT', 'KPI-LOAD', 'MEASURED_BY', '重量と容積の利用'),
('TERM-OTIF', 'KPI-OTIF', 'DEFINES', '指標の定義'),
('TERM-POD', 'RULE-006', 'EXPLAINED_BY', '証跡の提出期限'),
('TERM-COLDCHAIN', 'SVC-COLD', 'APPLIES_TO', '低温物流サービス'),
('TERM-SLA', 'FLOW-RECEIVE', 'APPLIES_TO', '契約条件の確認'),
('TERM-CROSSDOCK', 'FLOW-TRANSFER', 'APPLIES_TO', '中継工程'),
('TERM-LOADFACTOR', 'KPI-LOAD', 'DEFINES', '積載率の定義'),
('IND-CAPACITY', 'NEED-CAPACITY', 'MOTIVATES', '市場仮説から輸送力対策へ'),
('IND-TRACE', 'SVC-VISIBILITY', 'MOTIVATES', '証跡需要への対応仮説'),
('IND-GREEN', 'SVC-JOINT', 'MOTIVATES', '共同配送の提案仮説'),
('COMP-SNOW', 'RULE-003', 'COMPARED_WITH', '冬季対応と通知の比較軸'),
('COMP-DIGITAL', 'SVC-VISIBILITY', 'COMPARED_WITH', '追跡と証跡の比較軸'),
('COMP-JOINT', 'SVC-JOINT', 'COMPARED_WITH', '価格と混載品質の比較軸'),
('CODE-002', 'SVC-COLD', 'DEFINES', 'CHL温度帯'),
('CODE-003', 'FLOW-EXCEPTION', 'DEFINES', '例外コードの記録');

LOAD 'age';
SET search_path = ag_catalog, public;
SELECT * FROM cypher('business_knowledge', $$
  CREATE
    (CODE_001:Knowledge {code: 'CODE-001', kind: 'CODE', title: '青空運送のコード体系'}),
    (CODE_002:Knowledge {code: 'CODE-002', kind: 'CODE', title: '荷物・便・温度帯のコード'}),
    (CODE_003:Knowledge {code: 'CODE-003', kind: 'CODE', title: '例外と配送状態のコード'}),
    (TERM_OTIF:Knowledge {code: 'TERM-OTIF', kind: 'TERM', title: '納期内・全量納品率'}),
    (TERM_POD:Knowledge {code: 'TERM-POD', kind: 'TERM', title: '配達完了証跡'}),
    (TERM_CROSSDOCK:Knowledge {code: 'TERM-CROSSDOCK', kind: 'TERM', title: 'クロスドック'}),
    (TERM_LOADFACTOR:Knowledge {code: 'TERM-LOADFACTOR', kind: 'TERM', title: '積載率'}),
    (TERM_COLDCHAIN:Knowledge {code: 'TERM-COLDCHAIN', kind: 'TERM', title: 'コールドチェーン'}),
    (TERM_SLA:Knowledge {code: 'TERM-SLA', kind: 'TERM', title: 'サービス水準合意'}),
    (ORG_HQ:Knowledge {code: 'ORG-HQ', kind: 'ORG', title: '本社'}),
    (ORG_STRATEGY:Knowledge {code: 'ORG-STRATEGY', kind: 'ORG', title: '経営企画室'}),
    (ORG_SALES:Knowledge {code: 'ORG-SALES', kind: 'ORG', title: '営業本部'}),
    (ORG_OPS:Knowledge {code: 'ORG-OPS', kind: 'ORG', title: '運行本部'}),
    (ORG_QUALITY:Knowledge {code: 'ORG-QUALITY', kind: 'ORG', title: '品質管理室'}),
    (ORG_SAPPORO:Knowledge {code: 'ORG-SAPPORO', kind: 'ORG', title: '札幌センター'}),
    (ORG_TOKYO:Knowledge {code: 'ORG-TOKYO', kind: 'ORG', title: '東京ハブ'}),
    (ORG_IT:Knowledge {code: 'ORG-IT', kind: 'ORG', title: '情報システム室'}),
    (FLOW_RECEIVE:Knowledge {code: 'FLOW-RECEIVE', kind: 'FLOW', title: '受注・SLA確認'}),
    (FLOW_PLAN:Knowledge {code: 'FLOW-PLAN', kind: 'FLOW', title: '配車・便組成'}),
    (FLOW_PICKUP:Knowledge {code: 'FLOW-PICKUP', kind: 'FLOW', title: '集荷・検品'}),
    (FLOW_TRANSFER:Knowledge {code: 'FLOW-TRANSFER', kind: 'FLOW', title: '幹線輸送・中継'}),
    (FLOW_DELIVER:Knowledge {code: 'FLOW-DELIVER', kind: 'FLOW', title: '納品・POD登録'}),
    (FLOW_EXCEPTION:Knowledge {code: 'FLOW-EXCEPTION', kind: 'FLOW', title: '例外・荷主通知'}),
    (FLOW_BILLING:Knowledge {code: 'FLOW-BILLING', kind: 'FLOW', title: '請求・品質振り返り'}),
    (SVC_STANDARD:Knowledge {code: 'SVC-STANDARD', kind: 'SERVICE', title: 'あおぞら標準便'}),
    (SVC_COLD:Knowledge {code: 'SVC-COLD', kind: 'SERVICE', title: 'あおぞらチルド便'}),
    (SVC_JOINT:Knowledge {code: 'SVC-JOINT', kind: 'SERVICE', title: '地域共同配送'}),
    (SVC_VISIBILITY:Knowledge {code: 'SVC-VISIBILITY', kind: 'SERVICE', title: '配送可視化オプション'}),
    (CUST_FOOD:Knowledge {code: 'CUST-FOOD', kind: 'PARTNER', title: '北星フーズ'}),
    (CUST_RETAIL:Knowledge {code: 'CUST-RETAIL', kind: 'PARTNER', title: 'みらいマート'}),
    (CUST_PARTS:Knowledge {code: 'CUST-PARTS', kind: 'PARTNER', title: '東都精機'}),
    (RULE_001:Knowledge {code: 'RULE-001', kind: 'RULE', title: '通常配送の受付締切'}),
    (RULE_002:Knowledge {code: 'RULE-002', kind: 'RULE', title: '冷蔵品の温度管理'}),
    (RULE_003:Knowledge {code: 'RULE-003', kind: 'RULE', title: '北海道の冬季配送'}),
    (RULE_004:Knowledge {code: 'RULE-004', kind: 'RULE', title: '例外の第一報と判断権限'}),
    (RULE_005:Knowledge {code: 'RULE-005', kind: 'RULE', title: '共同配送の混載条件'}),
    (RULE_006:Knowledge {code: 'RULE-006', kind: 'RULE', title: 'PODの提供期限'}),
    (RULE_007:Knowledge {code: 'RULE-007', kind: 'RULE', title: '追加費用の承認'}),
    (RULE_008:Knowledge {code: 'RULE-008', kind: 'RULE', title: '旧POD翌営業日提供'}),
    (NEED_MARGIN:Knowledge {code: 'NEED-MARGIN', kind: 'MANAGEMENT_NEED', title: '低温配送の利益率改善'}),
    (NEED_QUALITY:Knowledge {code: 'NEED-QUALITY', kind: 'MANAGEMENT_NEED', title: '品質と収益の両立'}),
    (NEED_CAPACITY:Knowledge {code: 'NEED-CAPACITY', kind: 'MANAGEMENT_NEED', title: '繁忙期の輸送力確保'}),
    (NEED_FRESH:Knowledge {code: 'NEED-FRESH', kind: 'CUSTOMER_NEED', title: '北星フーズの鮮度・午前納品'}),
    (NEED_POD:Knowledge {code: 'NEED-POD', kind: 'CUSTOMER_NEED', title: 'みらいマートの検収省力化'}),
    (NEED_TRACE:Knowledge {code: 'NEED-TRACE', kind: 'CUSTOMER_NEED', title: '東都精機の緊急便可視化'}),
    (NEED_OFFLINE:Knowledge {code: 'NEED-OFFLINE', kind: 'FIELD_NEED', title: '通信断でも検品・PODを記録'}),
    (NEED_WAIT:Knowledge {code: 'NEED-WAIT', kind: 'FIELD_NEED', title: '待機と二重入力の削減'}),
    (NEED_AUTHORITY:Knowledge {code: 'NEED-AUTHORITY', kind: 'FIELD_NEED', title: '温度逸脱の判断先を明確化'}),
    (KPI_MARGIN:Knowledge {code: 'KPI-MARGIN', kind: 'KPI', title: '冷蔵便営業利益率'}),
    (KPI_OTIF:Knowledge {code: 'KPI-OTIF', kind: 'KPI', title: '店舗OTIF'}),
    (KPI_LOAD:Knowledge {code: 'KPI-LOAD', kind: 'KPI', title: '重量積載率'}),
    (KPI_TEMP:Knowledge {code: 'KPI-TEMP', kind: 'KPI', title: '温度逸脱率'}),
    (IND_CAPACITY:Knowledge {code: 'IND-CAPACITY', kind: 'INDUSTRY', title: '輸送力制約のシナリオ'}),
    (IND_TRACE:Knowledge {code: 'IND-TRACE', kind: 'INDUSTRY', title: '温度・配送証跡要求のシナリオ'}),
    (IND_GREEN:Knowledge {code: 'IND-GREEN', kind: 'INDUSTRY', title: '環境配慮調達のシナリオ'}),
    (COMP_SNOW:Knowledge {code: 'COMP-SNOW', kind: 'COMPETITOR', title: '白銀ロジの冬季配送'}),
    (COMP_DIGITAL:Knowledge {code: 'COMP-DIGITAL', kind: 'COMPETITOR', title: 'ネクストカーゴの可視化'}),
    (COMP_JOINT:Knowledge {code: 'COMP-JOINT', kind: 'COMPETITOR', title: 'つばさ共同便の混載'}),
    (CODE_001)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_STRATEGY),
    (CODE_002)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_OPS),
    (CODE_003)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_QUALITY),
    (TERM_OTIF)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_QUALITY),
    (TERM_POD)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_QUALITY),
    (TERM_CROSSDOCK)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_QUALITY),
    (TERM_LOADFACTOR)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_QUALITY),
    (TERM_COLDCHAIN)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_QUALITY),
    (TERM_SLA)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_QUALITY),
    (FLOW_RECEIVE)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_SALES),
    (FLOW_PLAN)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_OPS),
    (FLOW_PICKUP)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_TOKYO),
    (FLOW_TRANSFER)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_OPS),
    (FLOW_DELIVER)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_SAPPORO),
    (FLOW_EXCEPTION)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_QUALITY),
    (FLOW_BILLING)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_STRATEGY),
    (SVC_STANDARD)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_SALES),
    (SVC_COLD)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_SALES),
    (SVC_JOINT)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_SALES),
    (SVC_VISIBILITY)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_SALES),
    (CUST_FOOD)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_SALES),
    (CUST_RETAIL)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_SALES),
    (CUST_PARTS)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_SALES),
    (RULE_001)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_OPS),
    (RULE_002)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_QUALITY),
    (RULE_003)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_SAPPORO),
    (RULE_004)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_QUALITY),
    (RULE_005)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_OPS),
    (RULE_006)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_IT),
    (RULE_007)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_SALES),
    (RULE_008)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_IT),
    (NEED_MARGIN)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_STRATEGY),
    (NEED_QUALITY)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_STRATEGY),
    (NEED_CAPACITY)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_OPS),
    (NEED_FRESH)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_SALES),
    (NEED_POD)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_SALES),
    (NEED_TRACE)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_SALES),
    (NEED_OFFLINE)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_SAPPORO),
    (NEED_WAIT)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_OPS),
    (NEED_AUTHORITY)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_QUALITY),
    (KPI_MARGIN)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_STRATEGY),
    (KPI_OTIF)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_STRATEGY),
    (KPI_LOAD)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_STRATEGY),
    (KPI_TEMP)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_STRATEGY),
    (IND_CAPACITY)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_STRATEGY),
    (IND_TRACE)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_STRATEGY),
    (IND_GREEN)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_STRATEGY),
    (COMP_SNOW)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_STRATEGY),
    (COMP_DIGITAL)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_STRATEGY),
    (COMP_JOINT)-[:OWNED_BY {rationale: '情報の主管・問い合わせ先'}]->(ORG_STRATEGY),
    (ORG_STRATEGY)-[:REPORTS_TO {rationale: '本社の機能組織'}]->(ORG_HQ),
    (ORG_SALES)-[:REPORTS_TO {rationale: '本社の機能組織'}]->(ORG_HQ),
    (ORG_OPS)-[:REPORTS_TO {rationale: '本社の機能組織'}]->(ORG_HQ),
    (ORG_QUALITY)-[:REPORTS_TO {rationale: '本社の機能組織'}]->(ORG_HQ),
    (ORG_IT)-[:REPORTS_TO {rationale: '本社の機能組織'}]->(ORG_HQ),
    (ORG_SAPPORO)-[:REPORTS_TO {rationale: '運行本部が管轄する拠点'}]->(ORG_OPS),
    (ORG_TOKYO)-[:REPORTS_TO {rationale: '運行本部が管轄する拠点'}]->(ORG_OPS),
    (FLOW_RECEIVE)-[:NEXT {rationale: '通常配送の次工程'}]->(FLOW_PLAN),
    (FLOW_PLAN)-[:NEXT {rationale: '通常配送の次工程'}]->(FLOW_PICKUP),
    (FLOW_PICKUP)-[:NEXT {rationale: '通常配送の次工程'}]->(FLOW_TRANSFER),
    (FLOW_TRANSFER)-[:NEXT {rationale: '通常配送の次工程'}]->(FLOW_DELIVER),
    (FLOW_DELIVER)-[:NEXT {rationale: '通常配送の次工程'}]->(FLOW_BILLING),
    (FLOW_PICKUP)-[:ON_EXCEPTION {rationale: '温度逸脱・破損・遅延時の分岐'}]->(FLOW_EXCEPTION),
    (FLOW_TRANSFER)-[:ON_EXCEPTION {rationale: '温度逸脱・破損・遅延時の分岐'}]->(FLOW_EXCEPTION),
    (FLOW_DELIVER)-[:ON_EXCEPTION {rationale: '温度逸脱・破損・遅延時の分岐'}]->(FLOW_EXCEPTION),
    (SVC_COLD)-[:GOVERNED_BY {rationale: '冷蔵便の温度制約'}]->(RULE_002),
    (SVC_COLD)-[:GOVERNED_BY {rationale: '冷蔵便の証跡期限'}]->(RULE_006),
    (SVC_STANDARD)-[:GOVERNED_BY {rationale: '標準受付締切'}]->(RULE_001),
    (SVC_JOINT)-[:GOVERNED_BY {rationale: '混載の承認条件'}]->(RULE_005),
    (RULE_003)-[:EXTENDS {rationale: '冬季北海道の追加日数'}]->(RULE_001),
    (RULE_002)-[:ESCALATES_TO {rationale: '温度逸脱時の連絡と権限'}]->(RULE_004),
    (RULE_006)-[:SUPERSEDES {rationale: '2026年4月から提供期限を短縮'}]->(RULE_008),
    (FLOW_EXCEPTION)-[:GOVERNED_BY {rationale: '第一報30分以内・再開承認'}]->(RULE_004),
    (FLOW_DELIVER)-[:GOVERNED_BY {rationale: '納品後の証跡提供'}]->(RULE_006),
    (FLOW_PLAN)-[:GOVERNED_BY {rationale: '冬季北海道の配車判断'}]->(RULE_003),
    (FLOW_PLAN)-[:GOVERNED_BY {rationale: '混載の適合確認'}]->(RULE_005),
    (CUST_FOOD)-[:REQUESTS {rationale: '荷主の鮮度と納期要求'}]->(NEED_FRESH),
    (CUST_RETAIL)-[:REQUESTS {rationale: '検収省力化の要求'}]->(NEED_POD),
    (CUST_PARTS)-[:REQUESTS {rationale: '緊急便の要求'}]->(NEED_TRACE),
    (NEED_FRESH)-[:ADDRESSED_BY {rationale: '冷蔵便で温度条件を担保'}]->(SVC_COLD),
    (NEED_FRESH)-[:CONSTRAINED_BY {rationale: '午前納品と冬季遅延の調整が必要'}]->(RULE_003),
    (NEED_POD)-[:ADDRESSED_BY {rationale: '電子POD共有'}]->(SVC_VISIBILITY),
    (NEED_TRACE)-[:ADDRESSED_BY {rationale: '到着見込み共有'}]->(SVC_VISIBILITY),
    (NEED_MARGIN)-[:ADDRESSED_BY {rationale: '積載率向上で収益を改善する仮説'}]->(SVC_JOINT),
    (NEED_CAPACITY)-[:ADDRESSED_BY {rationale: '便を共同化し輸送力を確保'}]->(SVC_JOINT),
    (NEED_QUALITY)-[:CONSTRAINED_BY {rationale: '品質基準を削減しない'}]->(RULE_002),
    (NEED_MARGIN)-[:BALANCED_WITH {rationale: '収益改善で温度管理を省略しない'}]->(NEED_QUALITY),
    (NEED_OFFLINE)-[:ADDRESSED_BY {rationale: '端末保存と再同期'}]->(SVC_VISIBILITY),
    (NEED_WAIT)-[:ADDRESSED_BY {rationale: '受注時の予約枠合意'}]->(FLOW_RECEIVE),
    (NEED_AUTHORITY)-[:ADDRESSED_BY {rationale: '判断権限を明文化'}]->(RULE_004),
    (NEED_MARGIN)-[:MEASURED_BY {rationale: '月次利益率'}]->(KPI_MARGIN),
    (NEED_QUALITY)-[:MEASURED_BY {rationale: '温度逸脱率'}]->(KPI_TEMP),
    (NEED_FRESH)-[:MEASURED_BY {rationale: '荷主納期と欠品'}]->(KPI_OTIF),
    (SVC_JOINT)-[:MEASURED_BY {rationale: '重量と容積の利用'}]->(KPI_LOAD),
    (TERM_OTIF)-[:DEFINES {rationale: '指標の定義'}]->(KPI_OTIF),
    (TERM_POD)-[:EXPLAINED_BY {rationale: '証跡の提出期限'}]->(RULE_006),
    (TERM_COLDCHAIN)-[:APPLIES_TO {rationale: '低温物流サービス'}]->(SVC_COLD),
    (TERM_SLA)-[:APPLIES_TO {rationale: '契約条件の確認'}]->(FLOW_RECEIVE),
    (TERM_CROSSDOCK)-[:APPLIES_TO {rationale: '中継工程'}]->(FLOW_TRANSFER),
    (TERM_LOADFACTOR)-[:DEFINES {rationale: '積載率の定義'}]->(KPI_LOAD),
    (IND_CAPACITY)-[:MOTIVATES {rationale: '市場仮説から輸送力対策へ'}]->(NEED_CAPACITY),
    (IND_TRACE)-[:MOTIVATES {rationale: '証跡需要への対応仮説'}]->(SVC_VISIBILITY),
    (IND_GREEN)-[:MOTIVATES {rationale: '共同配送の提案仮説'}]->(SVC_JOINT),
    (COMP_SNOW)-[:COMPARED_WITH {rationale: '冬季対応と通知の比較軸'}]->(RULE_003),
    (COMP_DIGITAL)-[:COMPARED_WITH {rationale: '追跡と証跡の比較軸'}]->(SVC_VISIBILITY),
    (COMP_JOINT)-[:COMPARED_WITH {rationale: '価格と混載品質の比較軸'}]->(SVC_JOINT),
    (CODE_002)-[:DEFINES {rationale: 'CHL温度帯'}]->(SVC_COLD),
    (CODE_003)-[:DEFINES {rationale: '例外コードの記録'}]->(FLOW_EXCEPTION)
$$) AS (result agtype);
